baseURL       = "https://windsorlockhart.com/"
languageCode  = "en-us"
title         = "The Windsor Plaza at Lockhart, TX"
summarylength = 25

# Site Menus
[menu]
  # Navbar Menus
  [[menu.nav]]
    name    = "Home"
    url     = "/"
    weight  = 1
  [[menu.nav]]
    name    = "About"
    url     = "/about"
    weight  = 2
  [[menu.nav]]
    name    = "Project"
    url     = "/#project"
    weight  = 3
  [[menu.nav]]
    name    = "Get in touch"
    url     = "/contact"
    weight  = 4

# Site Params
[params]
  logo = "images/logo.png"
  dateFormat = "26 FEB 1994"
  # Meta data
  description = "Invest in the Windsor Plaza at Lockhart, TX"
  author = "Javier Robalino"
  # Google Analitycs
  googleAnalitycsID = "Your ID"
  # We're using formspree.io for form handling, paste your formspree url below
  fabform  = "https://formspree.io/f/mwkjvaaz"

  # Contact Form
  [params.contactForm]
    placeholder_first_name        = "First Name"
    placeholder_last_name         = "Last Name"
    placeholder_email             = "Email"
    placeholder_project_type      = "Investment Type"
    placeholder_about_the_project = "About Your Interest"
    send_message                  = "Send Message"

    [[params.contactForm.projectType]]
      value = "retail"
      title  = "Retail Tenant"
    [[params.contactForm.projectType]]
      value = "investor"
      title  = "Investor"
    [[params.contactForm.projectType]]
      value = "builder"
      title  = "Builder"
  
  # Navbar Action Button
  [params.navAction]
    status  = true
    name    = "Get in touch"
    url     = "contact"
  

  # Banner Section
  [params.banner]
    enable                = true
    background_image      = "images/backgrounds/texas.jpg"
    heading               = "Invest in the BBQ Capital of Texas"
    tagline               = "GROW WITH LOCKHART"
    primary_button        = "View the opportunity"
    primary_button_url    = "#project"
    secondary_button      = "Connect with Us"
    secondary_button_url  = "contact"

  [params.portfolio]
    enable    = true
    title     = "THE WINDSOR PLAZA AT LOCKHART"
    subtitle  = "Mixed retail opportunity adjacent to SH-130 and minutes from the Lockhart town square."

  [params.call_to_action]
    enable              = true
    background_image    = "images/backgrounds/cta-background.jpg"
    title               = "LET’S WORK TOGETHER"
    secondary_title     = "We develop with <span>diligence</span> to help our investors, tenants, and consumers gain <span>value</span>"
    primary_button      = "Connect"
    primary_button_url  = "contact"
    secondary_button    = "Show me more"
    secondary_button_url = "/#project"

  [params.footer]
    # Footer Contact Info
    [params.footer.contactInfo]
      title   = "Contact Info"
      address = "713 Elmwood St.<br>Prior Lake, MN 55372"
      phone   = "409-896-1444"
      email   = "info@roxo.co"
      # Footer Sitemap
      [params.footer.sitemap]
        title   = "Sitemap"
        [[params.footer.sitemap.link]]
          name = "Team"
          url  = "/about"
        [[params.footer.sitemap.link]]
          name = "Project"
          url  = "/#project"
        [[params.footer.sitemap.link]]
          name = "Contact"
          url  = "/contact"
      # Footer Social Media
      [params.footer.social]
        title   = "Social Media"
        [[params.footer.social.link]]
          name = "Instagram (coming soon)"
          url  = "#"
      # Footer Service
      [params.footer.service]
        title       = "We help investors: "
        description = "develop sustainable land<br>build community<br>create new experiences"